spring:
  #数据库设置
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/yeruicao?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT"
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: web.qq20001127

  #清空模板引擎缓存
  thymeleaf:
    cache: false


  #设置文件上传的大小限制
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 500MB

#首页路径
server:
  servlet:
    context-path: /yrc


